# Generated by Django 5.2.1 on 2025-06-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinfo',
            name='cars_count',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='exam_pass_rate',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='instructors_count',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='theory_pass_rate',
        ),
    ]
