# Generated by Django 5.2.1 on 2025-06-03 01:34

import main_page.models.main_page
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_remove_pageinfo_cars_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinfo',
            name='additional_services_subtitle',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='instructor_subtitle',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='services_subtitle',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='stage_subtitle',
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='reviews_video_title',
            field=models.CharField(default='test', max_length=100, verbose_name='Заголовок отзывы видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=main_page.models.main_page.WebPField(blank=True, null=True, upload_to='advantages/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='image',
            field=main_page.models.main_page.WebPField(blank=True, null=True, upload_to='instructors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='instructor_title',
            field=models.CharField(max_length=100, verbose_name='Заголовок инструкторы'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='start_education_image',
            field=main_page.models.main_page.WebPField(blank=True, null=True, upload_to='main_page/', verbose_name='Изображение начать обучение'),
        ),
    ]
