# Generated by Django 5.2.1 on 2025-06-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_remove_pageinfo_additional_services_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinfo',
            name='about_us_button',
            field=models.CharField(max_length=100, verbose_name='Текст кнопки о нас'),
        ),
    ]
