# Generated by Django 5.2.1 on 2025-06-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_pageinfo_about_us_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinfo',
            name='hotline_telephone',
            field=models.CharField(max_length=12, verbose_name='Горячая линия'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Телефон компании'),
        ),
    ]
