# Generated by Django 5.2.1 on 2025-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='Ссылка на видео')),
                ('service', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('other', 'Other')], max_length=20, verbose_name='Сервис')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='Превью')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='additionalservices',
            options={'verbose_name': 'Доп услуга', 'verbose_name_plural': 'Доп услуги'},
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='instructors',
            options={'verbose_name': 'Инструктор', 'verbose_name_plural': 'Инструктора'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='reviewsvideo',
            options={'verbose_name': 'Отзыв видео', 'verbose_name_plural': 'Отзывы видео'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='stages',
            options={'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
    ]
