# Generated by Django 5.2.1 on 2025-06-03 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_video_alter_additionalservices_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='reviewsvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='advantage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.video', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='google_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Google'),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='twogis_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на 2GIS'),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='yandex_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Yandex'),
        ),
        migrations.AddField(
            model_name='reviewsvideo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='advantage_type',
            field=models.CharField(choices=[('small', 'Небольшая информация'), ('big', 'Большая информация'), ('image', 'Картинка'), ('video', 'Видео')], max_length=50, verbose_name='Тип преимущества'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ссылка на видео'),
        ),
    ]
