# Generated by Django 5.2.1 on 2025-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_telegramsubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramSubscriber',
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
